# Generated by Django 5.2.6 on 2025-09-30 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_remove_lesson_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='test',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='materials.question', verbose_name='Вопрос'),
            preserve_default=False,
        ),
    ]
